language: node_js

node_js:
   - "10.15.0"

branches:
   only:
      - working # will only build for master branch commits

before_script:
   - npm install -g  firebase-tools # installs firebase to run firebase deploy
   - npm install -g  @angular/cli

script:
   - ng build --prod --aot

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive # firebase deploy after angular-cli build

notifications:
  email:
    on_failure: change
    on_success: change